name: Deploy Vite App to GitHub Pages

on:
  push:
    branches: ["main"] # Запускаем при каждом пуше в main
  workflow_dispatch:

# Настройки прав для публикации
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout кода
        uses: actions/checkout@v4

      - name: Установка Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Установка зависимостей
        run: npm install

      - name: Сборка проекта
        run: npm run build

      - name: Настройка GitHub Pages
        uses: actions/configure-pages@v4

      - name: Загрузка артефактов (папка dist)
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Деплой на GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
